{{- if .Values.serviceAccount.clusterRole }}
{{- $app_name := include "main.app_name" . }}
{{- $roleName := default $app_name .Values.serviceAccount.clusterRole.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{$roleName}}
rules:
{{ .Values.serviceAccount.clusterRole.rules | toYaml }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{(include "app_name")}}
subjects:
- kind: ServiceAccount
  name: {{(include "app_name")}}
  namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{$roleName}}
  apiGroup: rbac.authorization.k8s.io 
{{- end -}}