{{ $data := (lookup "v1" "Secret" .Release.Namespace "postgresql").data }}
{{- if and (not $data) }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
{{- $user_password := randAlphaNum 20 }}
  postgres-password: {{ randAlphaNum 20 | b64enc }}
  password: {{ $user_password | b64enc }}
  replication-password: {{ randAlphaNum 20 | b64enc }}
  database-url: {{ printf "postgres://plane:%s@%s-postgresql:5432/plane" $user_password .Release.Name | b64enc}}
{{- end }}